project:
  type: website
  output-dir: ../docs
execute:
  eval: false
  freeze: true

website:
  title: College Basketball Reddit Project
  sidebar:
    style: docked
    search: true
    contents:
      - section: "Project Overview"
        contents:
          - introduction.qmd
          - business_questions.ipynb
      - eda.qmd
      - nlp.qmd
      - ml.qmd
      - discussion.qmd
      - conclusion.qmd

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var author.name >}}] <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    embed-resources: true

