# Feedback

## Overview of our Feedback

On this project, we received feedback from both Professor Amit and from fellow students, which we implemented throughout the project. We did not receive explicit feedback on the Natural Language Processing (NLP) and Machine Learning (ML) pages because of the timing of the submissions; however, we extrapolated from the feedback on the project plans, Exploratory Data Analysis (EDA), and website/result sections to ensure that our project improved as much as possible based on the feedback we received.

## Feedback per Category

Below, we outline the feedback we received on each section:

### Project Plans
* Feedback on Project Plans: The feedback we received from the other student group was that our project plans were well-defined and interconnected with appropriate complexity. The feedback also stated that the business goals contained no technical language and that the external datasets aligned with answering these business goals. Professor Amit did not include any specific feedback on the Project Plans, so we tried to continue what we had done on the original Project Plans throughout the site.
* Implementation of Feedback on Project Plans: Because the student feedback group thought that we met expectations in the project plans sections, we continued to implement things that they thought were good throughout the project, especially as we adapted our business goals in the NLP and ML sections. We ensured that these new and adapted business goals still contained no technical language, and we continued to use our external dataset to create the narrative flow throughout the project that the group liked. Professor Amit’s feedback did not include anything specific to the project plans, so we were sure to continue doing what we had on some of the specific project plans throughout the website. This included ensuring any changes to business goals kept the non-technical language, and any changes to the technical proposals included specific mentions of which models we would use and any other coding techniques were specified.

### Exploratory Data Analysis (EDA)
* Feedback on EDA: The feedback we received from the other student group on the EDA section included changing our tables and charts to be interactive instead of stagnant; we thought this was great feedback. The group also suggested adding more description to the tables - we thought this was great feedback as well. Professor Amit’s feedback included some things that the student group touched on, including adding interactive charts and better formatting our tables.
* Implementation of Feedback on EDA: With the student feedback in mind, we attempted to make as many of the graphs and tables interactive as possible. Please see the EDA page for these interactive charts and tables. We really appreciated this feedback and thought it made our EDA page much more interesting and engaging. We also created tables with clearer labels and provided additional explanations for the tables verbally so that the conclusions of the tables were more clear to the readers. We also ensured that our color schemes were both visually appealing and were accessible to everyone. We appreciated the group’s feedback on the section, and implemented it throughout. We appreciated Professor Amit’s feedback as well, which generally aligned with the feedback from our peers, and incorporated it into both the EDA page and throughout the website to make sure our conclusions were displayed in interesting ways and that readers were engaged in our analysis.

### Natural Langauge Processing (NLP)
* Feedback on NLP: Although we did not receive feedback from the other student group on the NLP page because of the submission timelines, we were able to incorporate some of the feedback from the EDA sections into the NLP section. Professor Amit’s feedback didn’t touch on anything specific to NLP, so we were sure to incorporate his feedback of flagging any additional insights that we found in this section, as well as ensuring that this portion of the website was easy to navigate and visually appealing.
* Implementation of Feedback on NLP: We added increased descriptions to our tables and charts, and we focused on making our business goals have no technical language while ensuring that our technical proposals specified which models we would be using to accomplish our tasks. The feedback on the EDA section made our NLP section better as well.

### Machine Learning (ML)
* Feedback on ML: Similar to above, we were able to incorporate feedback from the student group on the EDA section and implement it into the ML section. Professor Amit’s feedback noted that if we found any insights outside of our initial business questions, we should highlight that and make that clear. Overall, we thought this was great feedback because it encouraged us to expand the scope of our project, and we incorporated this feedback throughout our website.
* Implementation of Feedback on ML: We added a new business question section, with new modeling and analysis, to increase our material and come to additional interesting conclusions using the data at hand. We continued to use our external data efficiently and ensured it tied to the narrative we were building throughout our project. We took some time to expand our ML section to include additional analysis, which included some of these additional insights Professor Amit suggested. We also were sure to flag anytime our business questions evolved over the course of the project, which happened a few times based on the data we had, which were also insights outside of our initial scope. 

### Website/Results
* Feedback on Website/Results: Our student feedback group had a few suggestions for how to improve the overall website and the results. The group suggested adding titles to the tables to ensure the readers understood what the tables meant; we incorporated that feedback on every page of the website so that each table has a title and is easy to understand for the readers. Professor Amit’s feedback suggested that the website could be made better by improving how visually appealing the site is and ensuring that the site is easy to navigate. 
* Implementation of Feedback on Website/Results: We also added other interactive tables to make each page more interesting and more fun for readers. We also ensured that the color schemes added onto the message that we wanted readers to take away from each portion. We addressed Professor Amit’s comments by improving the layout of the website, doing a better job of labeling charts and tables, and at times adjusting the color scheme of graphs and charts to make them more visually appealing. We also incorporated this feedback by reframing the EDA site, as the original project suggested, so that the EDA site mirrored the other pages in content and structure. We think these myriad changes improved the ease of navigation and visual nature of the website.

## Conclusions from Feedback
Overall, we thought the feedback was all extremely helpful, and we implemented all of it. We took on all of the feedback, and we even extrapolated the feedback from the EDA sections to the ML and NLP sections in order to ensure that our website was as good as possible. 